version: 2.1

orbs:
  micro-app: wealthsimple/micro-app@dev:master

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - micro-app/checkout:
          context: wealthsimple
          name: checkout
      - micro-app/security:
          context: wealthsimple
          name: security
          requires:
            - checkout
