# See https://dependabot.com/blog/introducing-config-files/
# This package is not under active development. Limit updates to security patches only.
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "widen_ranges"
    allowed_updates:
      - match:
          update_type: "security"
